### ISSUE TITLE
prevent deleting xdg `~/.config/user-dirs.dirs` directories

### ISSUE THREAD

**Issue by trappedinspacetime** [kaelzhang/shell-safe-rm#16]
First of all, thank you for coding such a useful tool. It would be good if it had preemtive non-deletion mechanism for user space essential directories, such as

       XDG_DESKTOP_DIR="$HOME/Desktop"
       XDG_DOWNLOAD_DIR="$HOME/Downloads"
       XDG_TEMPLATES_DIR="$HOME/Templates"
       XDG_PUBLICSHARE_DIR="$HOME/Public"
       XDG_DOCUMENTS_DIR="$HOME/Documents"
       XDG_MUSIC_DIR="$HOME/Music"
       XDG_PICTURES_DIR="$HOME/Pictures"
       XDG_VIDEOS_DIR="$HOME/Videos"

We can check the path of those directories with 

      xdg-user-dir DESKTOP
      xdg-user-dir DOWNLOAD
      xdg-user-dir TEMPLATES
      xdg-user-dir  PUBLICSHARE

**Comment by kaelzhang** [comment]
here https://github.com/kaelzhang/shell-safe-rm?tab=readme-ov-file#protect-files-and-directories-from-deleting
