### ISSUE TITLE
rm file in trash

### ISSUE THREAD

**Issue by wangyide** [kaelzhang/shell-safe-rm#24]
safe-rm should delete file which already in the recycle bin

**Comment by devhid** [comment]
Any update on this? It only makes sense to have safe-rm to have some option to permanently delete files that you do not need in the Trash.

**Comment by kaelzhang** [comment]
You could use custom conf file in `~/.safe-rm.conf`:

```sh
#!/bin/bash

export SAFE_RM_PERM_DEL_FILES_IN_TRASH=yes
```

**Comment by kaelzhang** [comment]
landed in `2.0.0`
