### ISSUE TITLE
⚠️ Running this will frequently delete the parent directory ⚠️

### ISSUE THREAD

**Issue by wparad** [kaelzhang/shell-safe-rm#28]
If you run this executable occasionally it will decide to delete the current working directory as well as the target.

I'm almost positive it was happening when running `safe-rm CHILD_DIRECTORY -rf` or `safe-rm ./CHILD_DIRECTORY -rf`, but I often would only find out ~10 minutes later that it happened when doing development that the directory I was in was no longer available. Or maybe it was putting the `-rf` first that caused the problem. One of these was the issue.

**Comment by adoyle-h** [comment]
How to reproduce this issue?

**Comment by wparad** [comment]
I'm almost positive it was happening when running `safe-rm CHILD_DIRECTORY -rf` or `safe-rm ./CHILD_DIRECTORY -rf`, but I often would only find out ~10 minutes later that it happened when doing development that the directory I was in was no longer available. Or maybe it was putting the `-rf` first that caused the problem. One of these was the issue.

**Comment by kaelzhang** [comment]
Could you provide concrete steps to reproduce the issue?

**Comment by kaelzhang** [comment]
Please reopen the issue for concrete cases
