### ISSUE TITLE
Merge safe-rm and shell-safe-rm

### ISSUE THREAD

**Issue by gl-yziquel** [kaelzhang/shell-safe-rm#30]
There has been discussion about merging these two tools, safe-rm and shell-safe-rm on launchpad:

https://bugs.launchpad.net/safe-rm/+bug/1940498

It suggests making a rewrite of shell-safe-rm in rust to provide a path forward for merging the two functionalities.

Would be very nice, honestly.

**Comment by kaelzhang** [comment]
Sorry, I don't have time to discuss with the author of this tool
