### ISSUE TITLE
IS THIS REPO ABBANDONED?

### ISSUE THREAD

**Issue by tapyu** [kaelzhang/shell-safe-rm#32]
It seems that this repo is abandoned as there is no response in from the user nor recent activity

![image](https://github.com/kaelzhang/shell-safe-rm/assets/22801918/844b977d-46f5-42c4-bac2-c38d2b18e18e)

I really need to use this repo. If you willing to get maintainers to keep this repo alive, I am available because I want to improve this code.

**Comment by kaelzhang** [comment]
I don't have much time to maintain open source projects due to life pressures, but however, I will maintain it time to time

Could you please provide concrete issues?

**Comment by kaelzhang** [comment]
@tapyu 

Actually you are always welcome to send pull requests, but before that let's discuss concrete issues or features first.
