### ISSUE TITLE
Version 2.0.0 archive URLs not working

### ISSUE THREAD

**Issue by pveierland** [kaelzhang/shell-safe-rm#38]
The download links for release version 2.0.0 are not working:

```
https://codeload.github.com/kaelzhang/shell-safe-rm/zip/2.0.0/tags/2.0.0
https://codeload.github.com/kaelzhang/shell-safe-rm/tar.gz/2.0.0/tags/2.0.0
```

The same links for release version 1.0.8 are working:
```
https://github.com/kaelzhang/shell-safe-rm/archive/refs/tags/1.0.8.zip
https://github.com/kaelzhang/shell-safe-rm/archive/refs/tags/1.0.8.tar.gz
```

**Comment by kaelzhang** [comment]
Weird, actually they are generated by github, not me

**Comment by kaelzhang** [comment]
Could you please use `git clone` to fetch source code instead for now?

**Comment by kaelzhang** [comment]
Seems github released a new asset domain that bugged

**Comment by pveierland** [comment]
That works for some use, however e.g. NixOS usage via the `fetchFromGitHub` source fetcher will fail with these archives. If possible it would be good to do a 2.0.1 release or retrigger the asset generation in some way.

**Comment by kaelzhang** [comment]
already deleted 2.0.0 and recreated again. not work. won't waste more time on this issue. since it is a github issue
