### ISSUE TITLE
Bad exit code (1) even though it succeeds and should be 0

### ISSUE THREAD

**Issue by asaf-erlich** [kaelzhang/shell-safe-rm#6]
To start my operating system is redhat 5 on a 64 bit virtual machine.  I cloned the repository and built it.

How to reproduce:
cd /tmp/
mkdir testdirectory
rm -rf testdirectory
echo $?

See it output 1

Uninstall safe-rm and you will see this should output 0.  Furthermore, even though it reports a bad exit code of 1 it successfully removes the directory as it should.

**Comment by kaelzhang** [comment]
Seems that the issue could be closed.
